import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from datetime import datetime
import os              # <-- ADD THIS
from dotenv import load_dotenv # <-- ADD THIS

load_dotenv()

def send_email_with_attachment(
    recipient_email,
    subject,
    body,
    sender_email=None,     # <-- MADE OPTIONAL
    sender_password=None,  # <-- MADE OPTIONAL
    attachment_data=None,
    attachment_name=None,
    smtp_server="smtp.gmail.com",
    smtp_port=587
):
    """
    Send email with optional CSV attachment
    
    Args:
        recipient_email: Recipient's email address
        subject: Email subject
        body: Email body text
        sender_email: (Optional) Sender's email. Defaults to .env var.
        sender_password: (Optional) Sender's password. Defaults to .env var.
        attachment_data: Data to attach (bytes or string)
        attachment_name: Name of attachment file
        smtp_server: SMTP server address
        smtp_port: SMTP server port
    
    Returns:
        True if successful, False otherwise
    """
    try:
        # --- START NEW LOGIC ---
        # If sender email/password aren't provided, get them from environment
        if sender_email is None:
            sender_email = os.getenv("APP_EMAIL_SENDER")
        if sender_password is None:
            sender_password = os.getenv("APP_EMAIL_PASSWORD")

        # Check if credentials exist
        if not sender_email or not sender_password:
            raise ValueError("Email credentials not provided and not set in .env file (APP_EMAIL_SENDER, APP_EMAIL_PASSWORD)")
        # --- END NEW LOGIC ---
        
        # Create message
        message = MIMEMultipart()
        message['From'] = sender_email
        message['To'] = recipient_email
        message['Subject'] = subject
        message['Date'] = datetime.now().strftime("%a, %d %b %Y %H:%M:%S")
        
        # Add body
        message.attach(MIMEText(body, 'plain'))
        
        # Add attachment if provided
        if attachment_data is not None and attachment_name is not None:
            if isinstance(attachment_data, str):
                attachment_data = attachment_data.encode('utf-8')
            
            attachment = MIMEApplication(attachment_data)
            attachment.add_header('Content-Disposition', 'attachment', filename=attachment_name)
            message.attach(attachment)
        
        # Connect to SMTP server and send email
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()  # Enable encryption
            server.login(sender_email, sender_password)
            server.send_message(message)
        
        return True
    
    except Exception as e:
        print(f"Error sending email: {e}")
        raise e

def send_summary_email(
    recipient_email,    # <-- REMOVED sender_email, sender_password
    results_summary,
    csv_data=None,
    smtp_server="smtp.gmail.com",
    smtp_port=587
):
    """
    Send summary email with results
    (Now fetches credentials automatically)
    """
    subject = f"Sentiment Analysis Results - {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    
    body = f"""
Sentiment Analysis Results
{'=' * 50}

{results_summary}

{'=' * 50}
Generated by Parallel Text Processing
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""
    
    attachment_name = f"sentiment_results_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
    
    # We don't pass sender_email or sender_password here.
    # The send_email_with_attachment function will get them from the .env file.
    return send_email_with_attachment(
        recipient_email=recipient_email,
        subject=subject,
        body=body,
        attachment_data=csv_data,
        attachment_name=attachment_name if csv_data else None,
        smtp_server=smtp_server,
        smtp_port=smtp_port
    )